import React, { useState } from 'react';
import { io } from 'socket.io-client';
import { Lock, Navigation } from 'lucide-react';
import toast from 'react-hot-toast';

const BACKEND_URL = window.location.hostname === 'localhost' ? 'http://localhost:3001' : 'https://pos-api.deziner4you.com';
const socket = io(BACKEND_URL);

interface Props {
  onAuthenticated: (user: any) => void;
}

export default function WaiterTerminalLogin({ onAuthenticated }: Props) {
  const [pin, setPin] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!pin) return toast.error('Enter a valid PIN');
    
    setLoading(true);
    
    try {
      const response = await socket.emitWithAck('auth_waiter_pin', { pin });
      if (response && response.success) {
        toast.success('Connected to POS successfully!');
        onAuthenticated({ name: 'Waiter Tablet', role: 'Waiter', store_id: response.store_id });
      } else {
        toast.error(response?.message || 'Invalid Waiter PIN');
      }
    } catch (err) {
      toast.error('Network error validating PIN');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-screen bg-slate-900 flex items-center justify-center p-4">
      <div className="bg-slate-800 p-8 rounded-3xl border border-slate-700 w-full max-w-sm shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500"></div>
        <div className="flex justify-center mb-6">
          <div className="w-20 h-20 bg-indigo-500/20 text-indigo-400 rounded-full flex items-center justify-center">
            <Navigation size={40} />
          </div>
        </div>
        <h2 className="text-3xl font-black text-white text-center mb-2">Tablet Pairing</h2>
        <p className="text-slate-400 text-sm text-center mb-8">Enter the 4-digit PIN generated by the Cashier POS to link this device.</p>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-2 uppercase tracking-wider">Pairing PIN</label>
            <input 
              type="text" 
              value={pin}
              onChange={e => setPin(e.target.value)}
              className="w-full bg-slate-900 border-2 border-slate-700 rounded-2xl p-4 text-white text-center text-3xl font-black tracking-widest focus:border-indigo-500 focus:outline-none transition-colors" 
              placeholder="0000"
              maxLength={4}
              required
              autoFocus
            />
          </div>
          <button 
            type="submit" 
            disabled={loading}
            className="w-full bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-4 rounded-xl transition-all shadow-lg hover:-translate-y-1 disabled:opacity-50"
          >
            {loading ? 'Verifying...' : 'Link Tablet'}
          </button>
        </form>
      </div>
    </div>
  );
}
